# Generated by Django 5.2.3 on 2025-06-23 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text="The user's input prompt")),
                ('response', models.TextField(help_text="The AI's generated response")),
                ('model_used', models.CharField(default='gpt-4.1', help_text='The AI model used for generation', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature setting for response generation')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used in the request', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to process the request in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the completion was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
            ],
            options={
                'verbose_name': 'AI Completion',
                'verbose_name_plural': 'AI Completions',
                'ordering': ['-created_at'],
            },
        ),
    ]
